
namespace RoyalCode.DomainEvents.Attributes;

/// <summary>
/// <para>
///     The context to handle domain events.
/// </para>
/// <para>
///     This enum is used by the <see cref="ObservesAttribute"/>.
/// </para>
/// </summary>
public enum EventHandlingContext
{
    /// <summary>
    /// <para>
    ///     It means that the event must be handled in the same transaction as the entities that generated the event.
    /// </para>
    /// <para>
    ///     The events must be generated by the same application or service.
    /// </para>
    /// </summary>
    InSameTransaction,

    /// <summary>
    /// <para>
    ///     It means that the event must be handled in a transaction separate 
    ///     from the transaction of the entities that generated the event.
    /// </para>
    /// <para>
    ///     This will be after the transaction with the entities generating the events has been successfully commited.
    /// </para>
    /// </summary>
    InNewTransaction
}

