# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: domain-nuget

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Build and pack Entities
        run: dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Entities/RoyalCode.Entities.csproj -c Release
        
      - name: Build and pack Domain Events
        run: dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.DomainEvents/RoyalCode.DomainEvents.csproj -c Release

      - name: Build and pack Aggregates
        run: dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Aggregates/RoyalCode.Aggregates.csproj -c Release
        
      - name: Publish
        run: dotnet nuget push ./**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
