# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: persistence-nuget

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build and pack Searches Abstractions
        run: sudo dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Searches.Abstractions/RoyalCode.Searches.Abstractions.csproj -c Release
             
      - name: Build and pack Search Persistence Abstractions
        run: sudo dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Persistence.Searches.Abstractions/RoyalCode.Searches.Persistence.Abstractions.csproj -c Release

      - name: Build and pack Search Persistence Linq
        run: sudo dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Searches.Persistence.Linq/RoyalCode.Searches.Persistence.Linq.csproj -c Release
                
      - name: Build and pack Persistence EF Search
        run: sudo dotnet build ./RoyalCode.EnterprisePatterns/RoyalCode.Persistence.EntityFramework.Searches/RoyalCode.Searches.Persistence.EntityFramework.csproj -c Release

      - name: Publish
        run: sudo dotnet nuget push ./**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
